name: studyapp
description: A simple language learning app for Tagalog and Cebuano sentence practice.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  dart_levenshtein: ^1.0.1
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  csv: ^6.0.0
  share_plus: ^11.0.0
  audioplayers: ^6.5.0
  speech_to_text: ^7.1.0
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.3.0
  intl: ^0.20.2
  string_similarity: ^2.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sentences_final.csv
    - assets/audio/
    - assets/mission.png